// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.MicroService.Data;

namespace eCommerce.MicroService.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20220122133249_dataupdatev2")]
    partial class dataupdatev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("eCommerce.MicroService.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 565, DateTimeKind.Local).AddTicks(3681),
                            Name = "Bilgisayar"
                        });
                });

            modelBuilder.Entity("eCommerce.MicroService.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified_At")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1464),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1496),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1499),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1501),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1503),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1510),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Created_At = new DateTime(2022, 1, 22, 16, 32, 49, 567, DateTimeKind.Local).AddTicks(1512),
                            Description = "AMD Ryzen 5 4600H 8GB 512GB SSD Windows 10 Home 16.1\" FHD Taşınabilir Bilgisayar",
                            Price = 9.499m,
                            ProductName = "Huawei Matebook D 16",
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("eCommerce.MicroService.Entities.Product", b =>
                {
                    b.HasOne("eCommerce.MicroService.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.MicroService.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
